#ifndef INTERFACECELLIDENTIFIER1D_H_INCLUDED
#define INTERFACECELLIDENTIFIER1D_H_INCLUDED

template < typename LATTICE >
class InterfaceCellIdentifier1D {
};

#endif // INTERFACECELLIDENTIFIER1D_H_INCLUDED
